// LanguageContext.jsx - Global Translation and Rebranding Context Provider
import React, { createContext, useState, useContext } from "react";

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};

const translations = {
  en: {
    // Brand Rebranding
    brand_name: "TADFANE RAFTING",
    brand_name_la: "ຕາດຟານ ລ່ອງແກ່ງ",
    brand_sub: "Rafting Trip Manager",
    system_sub: "Rafting Trip Manager & Employee Accounts (POS)",

    // Sidebar Menus
    dashboard: "Dashboard",
    ticket_sales: "Ticket Sales",
    trips_manifest: "Trips Manifest",
    customer_registration: "Customer Registration",
    commissions: "Commissions",
    guides_live: "Guides Live",
    drivers_live: "Drivers Live",
    boats_live: "Boats Live",
    reports: "Reports",
    financials: "Financials",
    settings: "Settings",
    logout: "Logout",

    // Login screen
    login_email_label: "Employee Email / Email Address",
    login_password_label: "Password",
    login_btn: "Sign In",
    demo_accounts: "Quick Test Accounts",
    login_error: "Invalid email or password!",

    // Inactivity warning
    inactivity_warning_title: "Session Warning",
    inactivity_warning_desc: "You have been inactive for 29 minutes. The system will log out in {time} seconds.",
    keep_working: "Keep Working",

    // Common labels / actions
    pax_unit: "Pax",
    bills_unit: "Bills",
    trips_unit: "Trips",
    passengers_today: "PASSENGERS TODAY",
    total_bills_today: "TOTAL BILLS TODAY",
    trips_today: "TRIPS TODAY",
    revenue_today: "REVENUE TODAY",
    revenue_month: "REVENUE MONTH",
    guide_wages: "GUIDE WAGES",
    driver_wages: "DRIVER WAGES",
    consolidated_report: "CONSOLIDATED REPORT",
    register_new_checkin: "New Check-In",
    system_alerts: "System Alerts",
    loading: "Loading...",

    // Receipt translations
    receipt_title: "POS Bill Preview",
    register_slip: "Register Slip",
    bill_number: "Bill Number",
    booking_id: "Booking ID",
    date: "Date",
    payment: "Payment Method",
    agent: "Agent / Partner",
    passengers: "Passengers",
    driver: "Driver",
    guides: "Guides",
    boats: "Boats",
    notes: "Notes",
    save_changes: "Save Changes",
    edit_label: "Edit",
    print_label: "Print",
    close_label: "Close",

    // Settings
    save_settings: "Save Settings",
    save_all_accounts: "Save Accounts",
    user_permissions_updated: "User accounts and permissions updated successfully!",
    system_settings_updated: "System settings updated!",
    user_added_success: "User added successfully! (Click Save Accounts below to commit)",
    user_deleted_success: "User deleted! (Click Save Accounts below to commit)",
    add_activity: "Add Activity",
    update_activity: "Update Activity",
    login_email: "Login Email",
    password: "Password",
    min_characters: "At least 6 characters",

    // POS Ticketing Complete Translations
    ticket_info_tab: "Ticket Info",
    passengers_tab: "Passengers",
    crew_tab: "Assign Crew",
    new_ticket_title: "Create Ticket Sales / POS",
    cust_name_label: "Customer / Leader Name",
    nation_label: "Nationality",
    age_label: "Age",
    gender_label: "Gender",
    phone_label: "Contact Phone",
    emergency_name_label: "Emergency Name",
    emergency_relation_label: "Relationship",
    emergency_phone_label: "Emergency Phone",
    date_label: "Date",
    time_label: "Time Slot",
    partner_label: "Agent / Partner",
    service_label: "Rafting Activity / Service",
    price_label: "Price",
    payment_method_label: "Payment Method",
    save_btn: "Save Changes",
    cancel_btn: "Cancel",
    confirm_btn: "Confirm",
    unassigned: "Unassigned",
    male: "Male",
    female: "Female",
    other: "Other",

    // Dashboard Completeness
    dashboard_title: "Dashboard Overview",
    dashboard_sub: "Daily operations overview and boat trip revenue statistics",
    daily_bookings: "DAILY BOOKINGS QUEUE",
    trip_manifest_list: "TRIPS MANIFEST LIST",
    all_status: "All Statuses",
    status_pending: "Pending Checkout",
    status_checkedin: "Ready for Dispatch",
    status_dispatched: "On Trip (Dispatched)",
    status_completed: "Completed",
    action_view_bill: "View Bill",
    action_edit: "Edit",
    action_print_bill: "Print Bill",
    action_print_slip: "Print Slip",
    action_print_sign: "Print Standee",
    action_dispatch: "Dispatch",

    // Reports Page
    reports_title: "Business Reports & Profit Summaries",
    reports_sub: "Comprehensive reports on bookings, commissions, costs, and profit breakdown",

    // Live Board Statuses
    available_short: "Avail",
    off_duty_short: "Off",
    ready_short: "Ready",
    not_ready_short: "Not Ready",
    ready_to_depart_short: "Ready",
    maintenance_short: "Maint",
    disabled_short: "Disabled",

    // Accounting / Payroll
    accounting_title: "Accounting & Expenses Portal",
    accounting_sub: "Income, operating expenses, financial reports, and payroll management",
    tab_income: "Income",
    tab_expenses: "Expenses",
    tab_pl: "Profit & Loss",
    tab_reports: "Reports",
    tab_monthly_summary: "Monthly Summary",
    tab_payroll_manager: "Staff & Payroll",
    tab_commission_manager: "Agent Commissions",
    monthly_summary_title: "Monthly Earnings Summary (Employees & Agents)",
    monthly_summary_sub: "Select a month to view detailed earnings, wages, and referral commission calculations.",
    select_month_label: "Select Month",
    employee_earnings_section: "Employee Monthly Earnings",
    agent_commissions_section: "Agent Referral Commissions",
    total_employee_payout: "Total Employee Payout",
    total_agent_commissions: "Total Agent Commissions",
    monthly_grand_total: "Monthly Grand Total",
    days_worked_col: "Days Worked",
    trip_wages_col: "Trip Wages",
    base_salary_col: "Base Salary",
    daily_wages_col: "Daily Wages",
    bonus_ot_comm_col: "Bonus/OT/Comm",
    total_earnings_col: "Total Earnings",
    print_monthly_summary: "Print Monthly Summary",
    run_payroll: "Run Payroll",
    print_statement: "Print Statement",
    pending_approval: "Pending Approval Queue",
    record_expense: "Record Operating Expense",
    save_expense: "Save Expense",
    general_expenses: "General Expenses Statement List",
    expense_category: "Expense Category",
    calculation_details: "Calculation Details",
    monthly_amount: "Monthly Amount (LAK)",
    total_expenses: "TOTAL OPERATING EXPENSES",
    total_revenue: "TOTAL REVENUE",
    gross_profit: "Gross Profit",
    net_profit: "Net Profit",
    agent_commissions_due: "Agent Commissions Due",
    wages_due: "Crew Wages Due",
    monthly_salaries: "Monthly Salaries",
    back_to_expenses: "Back to Expenses",
    back_to_income: "Back to Income",
    no_records: "No records found.",
        confirm_delete_expense: "Are you sure you want to delete this expense?",
    // Commission Tracker keys
    commission_report: "Referral Commission Summary",
    partner_name_col: "Partner / Agent Name",
    type_col: "Type",
    rate_col: "Rate",
    pax_count_col: "Referred Passengers",
    comm_due_col: "Commission Earned",
    action_col: "Manage",
    type_company: "Tour Company",
    type_agent: "Agent",
    type_guide: "Guide Referral",
    partner_details: "Referral Partner Details",
    contact_label: "Contact Info",
    rate_pax: "Commission Rate",
    total_referred: "Total Referred Passengers",
    total_commission: "Total Accumulated Commission",
    monthly_summary: "Monthly Commission Summary",
    no_monthly_history: "No monthly referral history.",
    pax_count_label: "Pax Count",
    clear_filter: "Clear Filter",
    edit_partner: "Edit Partner Details",
    add_partner: "Add New Partner",
    partner_name_field: "Tour Company / Agent Name",
    partner_name_placeholder: "e.g. Tad Fane Discoveries",
    partner_type_field: "Partner Type",
    commission_rate_field: "Commission Rate per Pax (LAK)",
    contact_info_field: "Contact Phone / Email",
    contact_info_placeholder: "e.g. +856 20 99998888",
    save_partner_btn: "Save Partner",
    cancel_partner_btn: "Cancel",
    confirm_delete_partner: "Are you sure you want to delete this partner?",
    referrals_monthly_title: "Referrals for",
                referrals_all_title: "All Referred Passengers",
    // QRBooking / POS keys
    ticket_sales_assignee: "Ticket Sales",
    tour_dispatch_assignee: "Tour Dispatch",
    select_multiple_guides: "Select one or more guides",
    select_multiple_boats: "Select one or more boats",
    select_one_driver: "Select exactly one driver",
    save_assignments: "Save Assignments",
    complete_trip: "Complete Trip",
    cancel_bill: "Cancel Bill",
    audit_logs_title: "Audit Logs:",
    edit_bill_desc: "Edit details, assign staff and passenger information",
    bill_details_tab: "Bill Details",
    audit_logs_tab: "Audit Logs",
    price_tier_label: "Price Tier (THB Activities)",
    price_tier1: "Standard Price (Tier 1 / Flat)",
    price_tier3: "Promo / Group Price (Tier 3)",
    custom_price_label: "Custom Price per Pax (Optional)",
    custom_price_placeholder: "Leave empty to use standard price",
    cash_payment: "Cash (LAK)",
    qr_payment: "Bank QR Transfer",
    notes_placeholder: "Any additional notes...",
    recalculated_total: "Recalculated Total:",
    flat_rate: "Flat",
    per_pax: "per Pax",
    passenger_number: "Passenger #",
    save_edits_btn: "Save Edits",
    cancel_edits_btn: "Cancel Edits",
    paid_bill_indicator: "Paid Bill",
    edit_paid_bill_audit: "Audit Logger Active (Editing Paid Bill)",
    billing_terminal: "Billing Terminal",
    search_bill_placeholder: "Scan or enter Bill Number / Booking Code...",
    new_booking_btn: "New Bill / Group",
    walkin_label: "Walk-in (General Guest)",
    no_crew_warning: "Boat crew and boat must be assigned first!",
    no_driver_warning: "No driver assigned.",
    print_bill_btn: "Print Bill",
    print_slip_btn: "Print Slip",
    print_standee_btn: "Print QR Sign",
    dispatch_boat_btn: "Dispatch Boat",
    status_registering: "Registering",
    status_cancelled: "Cancelled",
    registering_queue: "Registering Queue",
    ready_checkout_queue: "Ready to Checkout",
    // Dashboard keys
    payment_method_col: "Payment Method",
    driver_name_col: "Driver Name",
    customer_col: "Customer / Pax",
    commissions_type: "Commissions",
    printed_at: "Printed at",
    // Ticket Manifest keys
    select_trip_doc: "Select Boat Trip:",
    select_trip_option: "Select a Trip",
    group_bill: "Group Bill",
    individual_ticket: "Individual Tickets",
    boat_ticket: "Boat Ticket",
    passengers_list: "Passenger List",
    thank_you: "THANK YOU FOR USING OUR SERVICES",
    passenger_manifest_title: "Passenger Manifest",
    print_manifest: "Print Manifest",
    total_passengers: "Total Passengers",
    select_trip_preview: "Please select a boat trip from above to preview documents.",
    thank_you_short: "THANK YOU",
    boat_ride_insurance: "Boat Ride (Insurance Included)",
    reprint_bill_btn: "Reprint Bill",
    reprint_qr_btn: "Reprint QR",
    no_edits_logged: "No edits logged for this bill.",
    scan_qr_btn: "QR Scanner",
    enter_code_manually: "Enter Group Code Manually",
    group_code_placeholder: "e.g. REG-1234 or BK-1002",
    customer_instructions: "Instructions:",
    inst_step1: "1. Open mobile camera to scan this QR Code",
    inst_step2: "2. Accept safety terms",
    inst_step3: "3. Fill in details and click save",
    close_screen: "Close",
    confirm_cancel_bill: "Are you sure you want to cancel this bill?",
    bill_edits_saved_alert: "Bill edits saved successfully!",
    open_bill_btn: "Open",
    edit_details_audit: "Edit details, assign staff and passenger information",
    discount_label: "Discount",
    debt_label: "Outstanding Debt",
    net_total_label: "Net Total",
    actual_paid_label: "Actually Paid",
    payment_breakdown_title: "Payment Breakdown",
    total_discount_label: "Total Discounts",
    total_debt_label: "Total Outstanding Debt",
    cash_label: "Cash",
    transfer_label: "Transfer",
    card_label: "Card",
    bill_count_label: "Bills"
  },
  la: {
    // Brand Rebranding
    brand_name: "ຕາດຟານ ລ່ອງແກ່ງ",
    brand_name_la: "ຕາດຟານ ລ່ອງແກ່ງ",
    brand_sub: "ລະບົບຈັດການການລ່ອງແກ່ງ",
    system_sub: "ລະບົບຈັດການການລ່ອງແກ່ງ ແລະ ບັນຊີພະນັກງານ (POS)",

    // Sidebar Menus
    dashboard: "ໜ້າຫຼັກ",
    ticket_sales: "ຂາຍປີ້",
    trips_manifest: "ລາຍການຖ້ຽວ",
    customer_registration: "ລົງທະບຽນລູກຄ້າ",
    commissions: "ຄ່າຄອມເອເຈນ",
    guides_live: "ຕິດຕາມໄກດ໌",
    drivers_live: "ຕິດຕາມຄົນຂັບ",
    boats_live: "ຕິດຕາມເຮືອ",
    reports: "ລາຍງານ",
    financials: "ການເງິນ",
    settings: "ຕັ້ງຄ່າ",
    logout: "ອອກຈາກລະບົບ",

    // Login screen
    login_email_label: "ອີເມວພະນັກງານ / Email Address",
    login_password_label: "ລະຫັດຜ່ານ / Password",
    login_btn: "ເຂົ້າສູ່ລະບົບ / Sign In",
    demo_accounts: "ບັນຊີທົດລອງໃຊ້ງານ / Quick Test Accounts",
    login_error: "ອີເມວ ຫຼື ຣະຫັດຜ່ານບໍ່ຖືກຕ້ອງ!",

    // Inactivity warning
    inactivity_warning_title: "ແຈ້ງເຕືອນໝົດເວລາໃຊ້ງານ",
    inactivity_warning_desc: "ທ່ານບໍ່ມີການເຄື່ອນໄຫວເປັນເວລາ 29 ນາທີ. ລະບົບຈະອອກຈາກລະບົບໃນອີກ {time} ວິນາທີ.",
    keep_working: "ເຮັດວຽກຕໍ່ / Keep Working",

    // Common labels / actions
    pax_unit: "ຄົນ (Pax)",
    bills_unit: "ບິນ (Bills)",
    trips_unit: "ທ່ຽວ (Trips)",
    passengers_today: "ລູກຄ້າວັນນີ້ / PASSENGERS TODAY",
    total_bills_today: "ບິນທັງໝົດວັນນີ້ / TOTAL BILLS TODAY",
    trips_today: "ທ່ຽວເຮືອວັນນີ້ / TRIPS TODAY",
    revenue_today: "ລາຍຮັບວັນນີ້ / REVENUE TODAY",
    revenue_month: "ລາຍຮັບເດືອນນີ້ / REVENUE MONTH",
    guide_wages: "ຄ່າທ່ຽວໄກ້ດ / GUIDE WAGES",
    driver_wages: "ຄ່າທ່ຽວຄົນຂັບລົດ / DRIVER WAGES",
    consolidated_report: "ສະຫຼຸບຂໍ້ມູນທັງໝົດ / CONSOLIDATED REPORT",
    register_new_checkin: "Check-In ໃໝ່",
    system_alerts: "ແຈ້ງເຕືອນລະບົບ / System Alerts",
    loading: "ກຳລັງໂຫລດ...",

    // Receipt translations
    receipt_title: "ບິນຮັບເງິນ / POS Bill Preview",
    register_slip: "ບິນລົງທະບຽນລູກຄ້າ / Register Slip",
    bill_number: "ເລກບິນ / Bill Number",
    booking_id: "ລະຫັດການຈອງ / Booking ID",
    date: "ວັນທີ / Date",
    payment: "ການຊຳລະເງິນ / Payment",
    agent: "ຕົວແທນ / Agent",
    passengers: "ຜູ້ໂດຍສານ / Passengers",
    driver: "ຄົນຂັບ / Driver",
    guides: "ໄກດ໌ / Guides",
    boats: "ເຮືອ / Boats",
    notes: "ບັນທຶກ / Notes",
    save_changes: "ບັນທຶກການແກ້ໄຂ / Save Changes",
    edit_label: "ແກ້ໄຂ / Edit",
    print_label: "ພິມ / Print",
    close_label: "ປິດ / Close",

    // Settings
    save_settings: "ບັນທຶກການຕັ້ງຄ່າ / Save Settings",
    save_all_accounts: "ບັນທຶກຂໍ້ມູນບັນຊີທັງໝົດ / Save Accounts",
    user_permissions_updated: "ບັນທຶກຂໍ້ມູນບັນຊີຜູ້ໃຊ້ ແລະ ສິດພະນັກງານຮຽບຮ້ອຍ!",
    system_settings_updated: "ບັນທຶກການຕັ້ງຄ່າລະບົບຮຽບຮ້ອຍ!",
    user_added_success: "ເພີ່ມບັນຊີຜູ້ໃຊ້ພະນັກງານຮຽບຮ້ອຍ! (ກົດບັນທຶກບັນຊີດ້ານລຸ່ມເພື່ອບັນທຶກ)",
    user_deleted_success: "ລົບບັນຊີສຳເລັດ! (ກົດບັນທຶກບັນຊີດ້ານລຸ່ມເພື່ອບັນທຶກ)",
    add_activity: "ເພີ່ມກິດຈະກຳ / Add Activity",
    update_activity: "ບັນທຶກການແກ້ໄຂ / Update Activity",
    login_email: "ອີເມວເຂົ້າໃຊ້ງານ / Login Email",
    password: "ລະຫັດຜ່ານ / Password",
    min_characters: "ຢ່າງໜ້ອຍ 6 ຕົວອັກສອນ",

    // POS Ticketing Complete Translations
    ticket_info_tab: "ຂໍ້ມູນການຈອງ",
    passengers_tab: "ລາຍຊື່ຜູ້ໂດຍສານ",
    crew_tab: "ຈັດພະນັກງານ",
    new_ticket_title: "ລະບົບຂາຍປີ້ ແລະ ອອກບິນ / POS Terminal",
    cust_name_label: "ຊື່ລູກຄ້າ (ຫົວໜ້າກຸ່ມ)",
    nation_label: "ສັນຊາດ",
    age_label: "ອາຍຸ",
    gender_label: "ເພດ",
    phone_label: "ເບີໂທຕິດຕໍ່",
    emergency_name_label: "ຊື່ຜູ້ຕິດຕໍ່ສຸກເສີນ",
    emergency_relation_label: "ຄວາມສຳພັນ",
    emergency_phone_label: "ເບີໂທສຸກເສີນ",
    date_label: "ວັນທີເດີນທາງ",
    time_label: "ຮອບເວລາ",
    partner_label: "ຕົວແທນ / ເອເຈນ",
    service_label: "ກິດຈະກຳ / ບໍລິການ",
    price_label: "ລາຄາ (LAK)",
    payment_method_label: "ວິທີການຊຳລະເງິນ",
    save_btn: "ບັນທຶກຂໍ້ມູນ / Save",
    cancel_btn: "ຍົກເລີກ / Cancel",
    confirm_btn: "ຢືນຢັນ / Confirm",
    unassigned: "ຍັງບໍ່ໄດ້ກຳນົດ",
    male: "ຊາຍ",
    female: "ຍິງ",
    other: "ອື່ນໆ",

    // Dashboard Completeness
    dashboard_title: "ແຜງຄວບຄຸມ (Dashboard)",
    dashboard_sub: "ພາບລວມການດຳເນີນງານປະຈຳວັນ ແລະ ລາຍຮັບເຮືອທ່ອງທ່ຽວ",
    daily_bookings: "ຄິວການຈອງປະຈຳວັນ",
    trip_manifest_list: "ລາຍການຖ້ຽວເດີນທາງວັນນີ້",
    all_status: "ທຸກສະຖານະ",
    status_pending: "ລໍຖ້າຊຳລະເງິນ",
    status_checkedin: "ພ້ອມເດີນທາງ / Check-In",
    status_dispatched: "ກຳລັງເດີນທາງ",
    status_completed: "ສຳເລັດແລ້ວ",
    action_view_bill: "ເບິ່ງບິນ",
    action_edit: "ແກ້ໄຂ",
    action_print_bill: "ພິມໃບບິນ",
    action_print_slip: "ພິມໃບລົງທະບຽນ",
    action_print_sign: "ພິມປ້າຍ QR",
    action_dispatch: "ປ່ອຍເຮືອ",

    // Reports Page
    reports_title: "ລາຍງານການເງິນ ແລະ ສະຫຼຸບຜົນກຳໄລ",
    reports_sub: "ລາຍງານລາຍຮັບ-ລາຍຈ່າຍ ຄ່າຄອມມິດຊັນ ແລະ ສະຫຼຸບຜົນກຳໄລທັງໝົດ",

    // Live Board Statuses
    available_short: "ຫວ່າງ",
    off_duty_short: "ຢຸດງານ",
    ready_short: "ພ້ອມໃຊ້",
    not_ready_short: "ບໍ່ພ້ອມ",
    ready_to_depart_short: "ພ້ອມອອກ",
    maintenance_short: "ລໍຊ້ອມ",
    disabled_short: "ປິດໃຊ້",

    // Accounting / Payroll
    accounting_title: "ລະບົບບັນຊີ ແລະ ລາຍຈ່າຍ",
    accounting_sub: "ສະຫຼຸບລາຍຮັບ-ລາຍຈ່າຍ, ການອະນຸມັດວົງເງິນ ແລະ ຈັດການເງິນເດືອນ",
    tab_income: "ລາຍຮັບ",
    tab_expenses: "ລາຍຈ່າຍ",
    tab_pl: "ກຳໄລ-ຂາດທຶນ",
    tab_reports: "ລາຍງານ",
    tab_monthly_summary: "ສະຫຼຸບລາຍເດືອນ",
    tab_payroll_manager: "ເງິນເດືອນພະນັກງານ",
    tab_commission_manager: "ຄ່າຄອມເອເຈນ",
    monthly_summary_title: "ໃບສະຫຼຸບລາຍຮັບພະນັກງານ ແລະ ຄ່າຄອມເອເຈນ ປະຈຳເດືອນ",
    monthly_summary_sub: "ເລືອກເດືອນເພື່ອເບິ່ງລາຍລະອຽດການຄິດໄລ່ເງິນເດືອນ, ຄ່າທ່ຽວ ແລະ ຄ່າຄອມມິດຊັນ.",
    select_month_label: "ເລືອກເດືອນ",
    employee_earnings_section: "ລາຍຮັບພະນັກງານປະຈຳເດືອນ",
    agent_commissions_section: "ຄ່າຄອມມິດຊັນເອເຈນປະຈຳເດືອນ",
    total_employee_payout: "ລວມຈ່າຍພະນັກງານທັງໝົດ",
    total_agent_commissions: "ລວມຄ່າຄອມເອເຈນທັງໝົດ",
    monthly_grand_total: "ລວມລາຍຈ່າຍທັງໝົດປະຈຳເດືອນ",
    days_worked_col: "ວັນເຮັດວຽກ",
    trip_wages_col: "ເງິນຄ່າທ່ຽວ",
    base_salary_col: "ເງິນເດືອນພື້ນຖານ",
    daily_wages_col: "ຄ່າແຮງລາຍວັນ",
    bonus_ot_comm_col: "ໂບນັດ/OT/ຄອມ",
    total_earnings_col: "ລວມລາຍຮັບທັງໝົດ",
    print_monthly_summary: "ພິມສະຫຼຸບປະຈຳເດືອນ",
    run_payroll: "ຈັດການເງິນເດືອນ",
    print_statement: "ພິມລາຍງານ",
    pending_approval: "ລາຍການລໍຖ້າການອະນຸມັດ",
    record_expense: "ບັນທຶກລາຍຈ່າຍໃໝ່",
    save_expense: "ບັນທຶກລາຍຈ່າຍ",
    general_expenses: "ລາຍການລາຍຈ່າຍທົ່ວໄປ",
    expense_category: "ປະເພດລາຍຈ່າຍ",
    calculation_details: "ລາຍລະອຽດການຄຳນວນ",
    monthly_amount: "ຍອດເງິນປະຈຳເດືອນ (LAK)",
    total_expenses: "ລວມລາຍຈ່າຍທັງໝົດ",
    total_revenue: "ລວມລາຍຮັບທັງໝົດ",
    gross_profit: "ກຳໄລຂັ້ນຕົ້ນ",
    net_profit: "ກຳໄລສຸດທິ",
    agent_commissions_due: "ຄ່າຄອມມິດຊັນເອເຈນ",
    wages_due: "ຄ່າ allowance ພະນັກງານ",
    monthly_salaries: "ເງິນເດືອນພະນັກງານປະຈຳ",
    back_to_expenses: "ກັບຄືນສູ່ໜ້າລາຍຈ່າຍ",
    back_to_income: "ກັບຄືນສູ່ໜ້າລາຍຮັບ",
    no_records: "ບໍ່ມີຂໍ້ມູນ.",
    confirm_delete_expense: "ທ່ານຕ້ອງການລຶບລາຍຈ່າຍນີ້ແມ່ນບໍ່?",
    // Commission Tracker keys
    commission_report: "ລາຍງານຄ່າຄອມມິດຊັນສະສົມ / Commission Report",
    partner_name_col: "ຊື່ຄູ່ຄ້າ / Partner",
    type_col: "ປະເພດ / Type",
    rate_col: "ອັດຕາຄ່າຫົວ / Rate",
    pax_count_col: "ຜູ້ໂດຍສານສະສົມ / Passengers",
    comm_due_col: "ຍອດເງິນຄອມ / Commission",
    action_col: "ຈັດການ / Actions",
    type_company: "ບໍລິສັດທົວ / Tour Company",
    type_agent: "ເອເຈນ / Agent",
    type_guide: "ໄກ້ດແນະນຳ / Guide",
    partner_details: "ລາຍລະອຽດຄູ່ຄ້າ / Partner Details",
    contact_label: "ຕິດຕໍ່ / Contact",
    rate_pax: "ເລດຄ່າຄອມ / Rate",
    total_referred: "ລວມຜູ້ແນະນຳທັງໝົດ / Total Referred",
    total_commission: "ຍອດເງິນສະສົມທັງໝົດ / Total Commission",
    monthly_summary: "ສະຫຼຸບຍອດລາຍເດືອນ / Monthly Summary",
    no_monthly_history: "ຍັງບໍ່ມີປະຫວັດການສົ່ງຍອດລູກຄ້າລາຍເດືອນ.",
    pax_count_label: "ຈຳນວນຄົນ",
    clear_filter: "ລ້າງການກັ່ນຕອງ / Clear Filter",
    edit_partner: "ແກ້ໄຂຂໍ້ມູນຄູ່ຄ້າ / Edit Partner",
    add_partner: "ເພີ່ມບໍລິສັດຄູ່ຄ້າ / Add New Partner",
    partner_name_field: "ຊື່ອີເຈນ / ບໍລິສັດທົວ (Partner Name) *",
    partner_name_placeholder: "ຕົວຢ່າງ: ບໍລິສັດ ຕາດຟານ ດີດຄັຟເວີຣີ ຈຳກັດ",
    partner_type_field: "ປະເພດ (Type)",
    commission_rate_field: "ຄ່າຄອມຕໍ່ຫົວ / Rate (LAK) *",
    contact_info_field: "ເບີຕິດຕໍ່ / ລາຍລະອຽດ (Contact Info)",
    contact_info_placeholder: "ເບີໂທລະສັບ ຫຼື ອີເມວ",
    save_partner_btn: "ບັນທຶກຂໍ້ມູນຄູ່ຄ້າ / Save Partner",
    cancel_partner_btn: "ຍົກເລີກ / Cancel",
    confirm_delete_partner: "ທ່ານຕ້ອງການລົບຄູ່ຄ້ານີ້ແທ້ບໍ? / Delete partner?",
    referrals_monthly_title: "ລາຍຊື່ແນະນຳປະຈຳເດືອນ",
                referrals_all_title: "ລາຍຊື່ລູກຄ້າແນະນຳທັງໝົດ (All Referrals)",
    // QRBooking / POS keys
    ticket_sales_assignee: "ຜູ້ຮັບຜິດຊອບງານຂາຍປີ້ / Ticket Sales",
    tour_dispatch_assignee: "ຜູ້ຮັບຜິດຊອບຈັດໄກ້ດ / Tour Dispatch",
    select_multiple_guides: "ເລືອກໄດ້ຫຼາຍກວ່າ 1 ຄົນ",
    select_multiple_boats: "ເລືອກໄດ້ຫຼາຍກວ່າ 1 ລຳ",
    select_one_driver: "ເລືອກໄດ້ 1 ຄົນເທົ່ານັ້ນ",
    save_assignments: "ບັນທຶກການຈັດພະນັກງານ / Save Assignments",
    complete_trip: "ສຳເລັດທຣິບ / Complete Trip",
    cancel_bill: "ຍົກເລີກບິນ / Cancel Bill",
    audit_logs_title: "ປະຫວັດການແກ້ໄຂບິນ / Audit Logs:",
    edit_bill_desc: "ແກ້ໄຂລາຍລະອຽດ, ຈັດພະນັກງານ ແລະ ຂໍ້ມູນຜູ້ໂດຍສານ",
    bill_details_tab: "ລາຍລະອຽດບິນ / Bill Details",
    audit_logs_tab: "ປະຫວັດການແກ້ໄຂ / Audit Logs",
    price_tier_label: "ລະດັບລາຄາ / Price Tier",
    price_tier1: "ລາຄາເລີ່ມຕົ້ນ (Tier 1 / Flat)",
    price_tier3: "ລາຄາໂປຣໂມຊັ່ນ/ກຸ່ມໃຫຍ່ (Tier 3)",
    custom_price_label: "ລາຄາຕັ້ງເອງ / Custom Price",
    custom_price_placeholder: "ປະວ່າງໄວ້ເພື່ອໃຊ້ລາຄາເລີ່ມຕົ້ນ",
    cash_payment: "ເງິນສົດ / Cash (LAK)",
    qr_payment: "ແກນ QR / Bank QR Transfer",
    notes_placeholder: "ໝາຍເຫດເພີ່ມເຕີມ...",
    recalculated_total: "ລາຄາສຸດທິໃໝ່ / Recalculated Total:",
    flat_rate: "ເໝົາລຳ",
    per_pax: "ຕໍ່ຄົນ",
    passenger_number: "ຜູ້ໂດຍສານຄົນທີ",
    save_edits_btn: "ບັນທຶກການແກ້ໄຂ / Save Edits",
    cancel_edits_btn: "ຍົກເລີກການແກ້ໄຂ / Cancel Edits",
    paid_bill_indicator: "ບິນນີ້ຊຳລະເງິນແລ້ວ / Paid Bill",
    edit_paid_bill_audit: "ກຳລັງແກ້ໄຂຂໍ້ມູນບິນທີ່ຈ່າຍເງິນແລ້ວ (Audit Logger Active)",
    billing_terminal: "ລະບົບຂາຍປີ້ ແລະ ອອກບິນ / Billing Terminal",
    search_bill_placeholder: "ສະແກນ ຫຼື ປ້ອນເລກບິນ / ລະຫັດການຈອງ...",
    new_booking_btn: "ສ້າງບິນໃໝ່ / New Bill Group",
    walkin_label: "ລູກຄ້າທົ່ວໄປ (Walk-in)",
    no_crew_warning: "ກະລຸນາຈັດເຮືອ ແລະ ພະນັກງານກ່ອນປ່ອຍເຮືອ!",
    no_driver_warning: "ບໍ່ມີຄົນຂັບລົດ.",
    print_bill_btn: "ພິມໃບບິນ / Print Bill",
    print_slip_btn: "ພິມໃບລົງທະບຽນ / Print Slip",
    print_standee_btn: "ພິມປ້າຍ QR / Print QR Sign",
    dispatch_boat_btn: "ປ່ອຍເຮືອ / Dispatch Boat",
    status_registering: "ກຳລັງລົງທະບຽນ / Registering",
    status_cancelled: "ຍົກເລີກ / Cancelled",
    registering_queue: "ກຳລັງລົງທະບຽນ / Registering Queue",
    ready_checkout_queue: "ພ້ອມຊຳລະເງິນ / Ready to Checkout",
    // Dashboard keys
    payment_method_col: "ຊ່ອງທາງການຊຳລະ / Payment Method",
    driver_name_col: "ຄົນຂັບລົດ / Driver Name",
    customer_col: "ລູກຄ້າ / Pax",
    commissions_type: "ຄ່າຄອມ / Commissions",
    printed_at: "ພິມວັນທີ / Printed",
    // Ticket Manifest keys
    select_trip_doc: "ເລືອກທ່ຽວເຮືອເພື່ອສະແດງເອກະສານ / Select Boat Trip:",
    select_trip_option: "ເລືອກທ່ຽວເຮືອ (Select a Trip)",
    group_bill: "ບິນລວມກຸ່ມ / Group Bill",
    individual_ticket: "ປີ້ແຍກຄົນ / Individual Tickets",
    boat_ticket: "ປີ້ເຮືອ / Boat Ticket",
    passengers_list: "ລາຍຊື່ຜູ້ໂດຍສານ / Passenger List",
    thank_you: "ຂອບໃຈທີ່ໃຊ້ບໍລິການ / THANK YOU",
    passenger_manifest_title: "ໃບສະແດງລາຍຊື່ຜູ້ໂດຍສານ / Passenger Manifest",
    print_manifest: "ພິມໃບລາຍຊື່ / Print Manifest",
    total_passengers: "ຜູ້ໂດຍສານທັງໝົດ / Total Passengers",
    select_trip_preview: "ກະລຸນາເລືອກທ່ຽວເຮືອດ້ານເທິງເພື່ອສະແດງເອກະສານ / Select a trip to preview",
    thank_you_short: "ຂອບໃຈ / THANK YOU",
    boat_ride_insurance: "ລ່ອງເຮືອ (ລວມປະກັນໄພ) / Boat Ride & Insurance",
    reprint_bill_btn: "ພິມໃບບິນ / Reprint Bill",
    reprint_qr_btn: "ພິມສລິບ QR / Reprint QR",
    no_edits_logged: "ບໍ່ມີປະຫວັດການແກ້ໄຂບິນ / No edits logged for this bill.",
    scan_qr_btn: "ສະແກນ QR Code / QR Scanner",
    enter_code_manually: "ປ້ອນລະຫັດກຸ່ມ ຫຼື ສະແກນຜ່ານສາຍ USB / Enter Group Code Manually",
    group_code_placeholder: "ເຊັ່ນ: REG-1234 ຫຼື BK-1002",
    customer_instructions: "ຄຳແນະນຳສຳລັບລູກຄ້າ / Instructions:",
    inst_step1: "1. ເປີດກ້ອງມືຖືສະແກນ QR Code ນີ້ / 1. Open mobile camera to scan this QR Code",
    inst_step2: "2. ກົດຍອມຮັບເງື່ອນໄຂຄວາມປອດໄພ / 2. Accept safety terms",
    inst_step3: "3. ກອກຂໍ້ມູນສ່ວນຕົວໃຫ້ຄົບຖ້ວນທຸກຄົນ ແລ້ວກົດບັນທຶກ / 3. Fill details and save",
    close_screen: "ປິດໜ້າຈໍນີ້ / Close",
    confirm_cancel_bill: "ທ່ານຕ້ອງການຍົກເລີກບິນນີ້ແມ່ນຫຼືບໍ່? / Are you sure you want to cancel this bill?",
    bill_edits_saved_alert: "ບັນທຶກການແກ້ໄຂບິນສຳເລັດແລ້ວ! / Bill edits saved successfully!",
    open_bill_btn: "ເປີດບິນ / Open",
    edit_details_audit: "ແກ້ໄຂລາຍລະອຽດ, ຈັດພະນັກງານ ແລະ ຂໍ້ມູນຜູ້ໂດຍສານ / Edit details & assign staff",
    discount_label: "ສ່ວນຫຼຸດ",
    debt_label: "ຄ້າງຊຳລະ",
    net_total_label: "ຍອດສຸທິ",
    actual_paid_label: "ຈ່າຍຕົວຈິງ",
    payment_breakdown_title: "ສະຫຼຸບຊ່ອງທາງຊຳລະ",
    total_discount_label: "ສ່ວນຫຼຸດລວມ",
    total_debt_label: "ຄ້າງຊຳລະລວມ",
    cash_label: "ເງິນສົດ",
    transfer_label: "ໂອນເງິນ",
    card_label: "ບັດ",
    bill_count_label: "ບິນ"
  },
  th: {
    // Brand Rebranding
    brand_name: "ตาดฟาน ล่องแก่ง",
    brand_name_la: "ตาดฟาน ล่องแก่ง",
    brand_sub: "ระบบจัดการการล่องแก่ง",
    system_sub: "ระบบจัดการการล่องแก่ง & บัญชีพนักงาน (POS)",

    // Sidebar Menus
    dashboard: "หน้าแรก",
    ticket_sales: "ขายตั๋ว",
    trips_manifest: "รายการเที่ยวเรือ",
    customer_registration: "ลงทะเบียนลูกค้า",
    commissions: "ค่าคอมมิชชั่นเอเจนท์",
    guides_live: "ติดตามไกด์",
    drivers_live: "ติดตามคนขับ",
    boats_live: "ติดตามเรือ",
    reports: "รายงาน",
    financials: "การเงิน",
    settings: "ตั้งค่า",
    logout: "ออกจากระบบ",

    // Login screen
    login_email_label: "อีเมลพนักงาน / Email Address",
    login_password_label: "รหัสผ่าน",
    login_btn: "เข้าสู่ระบบ",
    demo_accounts: "บัญชีทดลองใช้งาน",
    login_error: "อีเมลหรือรหัสผ่านไม่ถูกต้อง!",

    // Inactivity warning
    inactivity_warning_title: "แจ้งเตือนหมดเวลาใช้งาน",
    inactivity_warning_desc: "คุณไม่มีความเคลื่อนไหวเป็นเวลา 29 นาที ระบบจะออกจากระบบในอีก {time} วินาที",
    keep_working: "ทำงานต่อ",

    // Common labels / actions
    pax_unit: "คน",
    bills_unit: "บิล",
    trips_unit: "เที่ยว",
    passengers_today: "ลูกค้าวันนี้",
    total_bills_today: "บิลทั้งหมดวันนี้",
    trips_today: "เที่ยวเรือวันนี้",
    revenue_today: "รายได้วันนี้",
    revenue_month: "รายได้เดือนนี้",
    guide_wages: "ค่าเที่ยวไกด์",
    driver_wages: "ค่าเที่ยวคนขับรถ",
    consolidated_report: "สรุปข้อมูลทั้งหมด",
    register_new_checkin: "เช็คอินใหม่",
    system_alerts: "แจ้งเตือนระบบ",
    loading: "กำลังโหลด...",

    // Receipt translations
    receipt_title: "บิลรับเงิน / POS Bill Preview",
    register_slip: "บิลลงทะเบียนลูกค้า / Register Slip",
    bill_number: "เลขบิล",
    booking_id: "รหัสการจอง",
    date: "วันที่",
    payment: "การชำระเงิน",
    agent: "ตัวแทน / เอเจนท์",
    passengers: "ผู้โดยสาร",
    driver: "คนขับรถ",
    guides: "ไกด์",
    boats: "เรือ",
    notes: "บันทึก",
    save_changes: "บันทึกการแก้ไข",
    edit_label: "แก้ไข",
    print_label: "พิมพ์",
    close_label: "ปิด",

    // Settings
    save_settings: "บันทึกการตั้งค่า",
    save_all_accounts: "บันทึกข้อมูลบัญชีทั้งหมด",
    user_permissions_updated: "บันทึกข้อมูลบัญชีผู้ใช้และสิทธิ์พนักงานเรียบร้อย!",
    system_settings_updated: "บันทึกการตั้งค่าระบบเรียบร้อย!",
    user_added_success: "เพิ่มบัญชีพนักงานเรียบร้อย! (คลิกบันทึกบัญชีด้านล่างเพื่อยืนยัน)",
    user_deleted_success: "ลบบัญชีสำเร็จ! (คลิกบันทึกบัญชีด้านล่างเพื่อยืนยัน)",
    add_activity: "เพิ่มกิจกรรม",
    update_activity: "บันทึกการแก้ไข",
    login_email: "อีเมลเข้าใช้งาน",
    password: "รหัสผ่าน",
    min_characters: "อย่างน้อย 6 ตัวอักษร",

    // POS Ticketing Complete Translations
    ticket_info_tab: "ข้อมูลการจอง",
    passengers_tab: "รายชื่อผู้โดยสาร",
    crew_tab: "จัดพนักงาน",
    new_ticket_title: "ระบบขายตั๋วและออกบิล / POS Terminal",
    cust_name_label: "ชื่อลูกค้า (หัวหน้ากลุ่ม)",
    nation_label: "สัญชาติ",
    age_label: "อายุ",
    gender_label: "เพศ",
    phone_label: "เบอร์โทรติดต่อ",
    emergency_name_label: "ชื่อผู้ติดต่อฉุกเฉิน",
    emergency_relation_label: "ความสัมพันธ์",
    emergency_phone_label: "เบอร์โทรฉุกเฉิน",
    date_label: "วันที่เดินทาง",
    time_label: "รอบเวลา",
    partner_label: "ตัวแทน / เอเจนท์",
    service_label: "กิจกรรม / บริการ",
    price_label: "ราคา (LAK)",
    payment_method_label: "วิธีการชำระเงิน",
    save_btn: "บันทึกข้อมูล / Save",
    cancel_btn: "ยกเลิก / Cancel",
    confirm_btn: "ยืนยัน / Confirm",
    unassigned: "ยังไม่ได้กำหนด",
    male: "ชาย",
    female: "หญิง",
    other: "อื่นๆ",

    // Dashboard Completeness
    dashboard_title: "แผงควบคุม (Dashboard)",
    dashboard_sub: "ภาพรวมการดำเนินงานประจำวันและรายรับเรือท่องเที่ยว",
    daily_bookings: "คิวการจองประจำวัน",
    trip_manifest_list: "รายการเที่ยวเดินทางวันนี้",
    all_status: "ทุกสถานะ",
    status_pending: "รอชำระเงิน",
    status_checkedin: "พร้อมเดินทาง / Check-In",
    status_dispatched: "กำลังเดินทาง",
    status_completed: "เสร็จสิ้นแล้ว",
    action_view_bill: "ดูบิล",
    action_edit: "แก้ไข",
    action_print_bill: "พิมพ์ใบเสร็จ",
    action_print_slip: "พิมพ์ใบลงทะเบียน",
    action_print_sign: "พิมพ์ป้าย QR",
    action_dispatch: "ปล่อยเรือ",

    // Reports Page
    reports_title: "รายงานการเงินและสรุปผลกำไร",
    reports_sub: "รายงานรายรับ-รายจ่าย ค่าคอมมิชชั่น และสรุปผลกำไรทั้งหมด",

    // Live Board Statuses
    available_short: "ว่าง",
    off_duty_short: "หยุดงาน",
    ready_short: "พร้อมใช้",
    not_ready_short: "ไม่พร้อม",
    ready_to_depart_short: "พร้อมออก",
    maintenance_short: "ซ่อมบำรุง",
    disabled_short: "ปิดใช้งาน",

    // Accounting / Payroll
    accounting_title: "ระบบบัญชีและรายจ่าย",
    accounting_sub: "สรุปรายรับ-รายจ่าย, การอนุมัติวงเงิน และจัดการเงินเดือน",
    tab_income: "รายรับ",
    tab_expenses: "รายจ่าย",
    tab_pl: "กำไร-ขาดทุน",
    tab_reports: "รายงาน",
    tab_monthly_summary: "สรุปรายเดือน",
    tab_payroll_manager: "เงินเดือนพนักงาน",
    tab_commission_manager: "ค่าคอมเอเจ้นต์",
    monthly_summary_title: "สรุปรายได้พนักงานและค่าคอมมิชชั่นเอเจ้นต์รายเดือน",
    monthly_summary_sub: "เลือกเดือนเพื่อดูรายละเอียดการคำนวณเงินเดือน ค่าเที่ยว และค่าคอมมิชชั่นของเอเจ้นต์",
    select_month_label: "เลือกเดือน",
    employee_earnings_section: "รายได้พนักงานประจำเดือน",
    agent_commissions_section: "ค่าคอมมิชชั่นเอเจ้นต์ประจำเดือน",
    total_employee_payout: "ยอดจ่ายพนักงานทั้งหมด",
    total_agent_commissions: "ยอดจ่ายค่าคอมเอเจ้นต์ทั้งหมด",
    monthly_grand_total: "ยอดรวมรายจ่ายประจำเดือนทั้งหมด",
    days_worked_col: "จำนวนวันทำงาน",
    trip_wages_col: "เงินค่าเที่ยว",
    base_salary_col: "เงินเดือนพื้นฐาน",
    daily_wages_col: "ค่าแรงรายวัน",
    bonus_ot_comm_col: "โบนัส/OT/คอมฯ",
    total_earnings_col: "รวมรายได้ทั้งหมด",
    print_monthly_summary: "พิมพ์สรุปประจำเดือน",
    run_payroll: "จัดการเงินเดือน",
    print_statement: "พิมพ์รายงาน",
    pending_approval: "รายการรออนุมัติ",
    record_expense: "บันทึกรายจ่ายใหม่",
    save_expense: "บันทึกรายจ่าย",
    general_expenses: "รายการรายจ่ายทั่วไป",
    expense_category: "ประเภทรายจ่าย",
    calculation_details: "รายละเอียดการคำนวณ",
    monthly_amount: "ยอดเงินประจำเดือน (LAK)",
    total_expenses: "รวมรายจ่ายทั้งหมด",
    total_revenue: "รวมรายรับทั้งหมด",
    gross_profit: "กำไรขั้นต้น",
    net_profit: "กำไรสุทธิ",
    agent_commissions_due: "ค่าคอมมิชชั่นเอเจนท์",
    wages_due: "ค่า allowance พนักงาน",
    monthly_salaries: "เงินเดือนพนักงานประจำ",
    back_to_expenses: "กลับสู่หน้ารายจ่าย",
    back_to_income: "กลับสู่หน้ารายรับ",
    no_records: "ไม่มีข้อมูล.",
    confirm_delete_expense: "คุณต้องการลบรายจ่ายนี้ใช่หรือไม่?",

    // Commission Tracker keys
    commission_report: "รายงานค่าคอมมิชชั่นสะสม / Commission Report",
    partner_name_col: "ชื่อคู่ค้า / Partner",
    type_col: "ประเภท / Type",
    rate_col: "อัตราต่อหัว / Rate",
    pax_count_col: "ผู้โดยสารสะสม / Passengers",
    comm_due_col: "ยอดเงินคอม / Commission",
    action_col: "จัดการ / Actions",
    type_company: "บริษัททัวร์ / Tour Company",
    type_agent: "เอเจนท์ / Agent",
    type_guide: "ไกด์แนะนำ / Guide",
    partner_details: "รายละเอียดคู่ค้า / Partner Details",
    contact_label: "ติดต่อ / Contact",
    rate_pax: "เรทค่าคอม / Rate",
    total_referred: "รวมผู้แนะนำทั้งหมด / Total Referred",
    total_commission: "ยอดเงินสะสมทั้งหมด / Total Commission",
    monthly_summary: "สรุปยอดรายเดือน / Monthly Summary",
    no_monthly_history: "ยังไม่มีประวัติการส่งยอดลูกค้าคนนี้รายเดือน",
    pax_count_label: "จำนวนคน",
    clear_filter: "ล้างการกรอง / Clear Filter",
    edit_partner: "แก้ไขข้อมูลคู่ค้า / Edit Partner",
    add_partner: "เพิ่มบริษัทคู่ค้า / Add New Partner",
    partner_name_field: "ชื่อเอเจนท์ / บริษัททัวร์ (Partner Name) *",
    partner_name_placeholder: "ตัวอย่าง: บริษัท ตาดฟาน ดิสคัฟเวอรี จำกัด",
    partner_type_field: "ประเภท (Type)",
    commission_rate_field: "ค่าคอมต่อหัว / Rate (LAK) *",
    contact_info_field: "เบอร์ติดต่อ / รายละเอียด (Contact Info)",
    contact_info_placeholder: "เบอร์โทรศัพท์ หรือ อีเมล",
    save_partner_btn: "บันทึกข้อมูลคู่ค้า / Save Partner",
    cancel_partner_btn: "ยกเลิก / Cancel",
    confirm_delete_partner: "คุณต้องการลบคู่ค้านี้ใช่หรือไม่? / Delete partner?",
    referrals_monthly_title: "รายชื่อแนะนำประจำเดือน",
    referrals_all_title: "รายชื่อลูกค้าแนะนำทั้งหมด (All Referrals)",

    // QRBooking / POS keys
    ticket_sales_assignee: "ผู้รับผิดชอบงานขายตั๋ว / Ticket Sales",
    tour_dispatch_assignee: "ผู้รับผิดชอบจัดไกด์ / Tour Dispatch",
    select_multiple_guides: "เลือกได้มากกว่า 1 คน",
    select_multiple_boats: "เลือกได้มากกว่า 1 ลำ",
    select_one_driver: "เลือกได้ 1 คนเท่านั้น",
    save_assignments: "บันทึกการจัดพนักงาน / Save Assignments",
    complete_trip: "เสร็จสิ้นทริป / Complete Trip",
    cancel_bill: "ยกเลิกบิล / Cancel Bill",
    audit_logs_title: "ประวัติการแก้ไขบิล / Audit Logs:",
    edit_bill_desc: "แก้ไขรายละเอียด, จัดพนักงาน และข้อมูลผู้โดยสาร",
    bill_details_tab: "รายละเอียดบิล / Bill Details",
    audit_logs_tab: "ประวัติการแก้ไข / Audit Logs",
    price_tier_label: "ระดับราคา / Price Tier",
    price_tier1: "ราคาเริ่มต้น (Tier 1 / Flat)",
    price_tier3: "ราคาโปรโมชั่น/กลุ่มใหญ่ (Tier 3)",
    custom_price_label: "ราคาตั้งเอง / Custom Price",
    custom_price_placeholder: "ปล่อยว่างไว้เพื่อใช้ราคาเริ่มต้น",
    cash_payment: "เงินสด / Cash (LAK)",
    qr_payment: "สแกน QR / Bank QR Transfer",
    notes_placeholder: "หมายเหตุเพิ่มเติม...",
    recalculated_total: "ราคาสุทธิใหม่ / Recalculated Total:",
    flat_rate: "เหมาลำ",
    per_pax: "ต่อคน",
    passenger_number: "ผู้โดยสารคนที่",
    save_edits_btn: "บันทึกการแก้ไข / Save Edits",
    cancel_edits_btn: "ยกเลิกการแก้ไข / Cancel Edits",
    paid_bill_indicator: "บิลนี้ชำระเงินแล้ว / Paid Bill",
    edit_paid_bill_audit: "กำลังแก้ไขข้อมูลบิลที่จ่ายเงินแล้ว (Audit Logger Active)",
    billing_terminal: "ระบบขายตั๋วและออกบิล / Billing Terminal",
    search_bill_placeholder: "สแกนหรือป้อนเลขบิล / รหัสการจอง...",
    new_booking_btn: "สร้างบิลใหม่ / New Bill Group",
    walkin_label: "ลูกค้าทั่วไป (Walk-in)",
    no_crew_warning: "กรุณาจัดเรือและพนักงานก่อนปล่อยเรือ!",
    no_driver_warning: "ไม่มีคนขับรถ",
    print_bill_btn: "พิมพ์ใบเสร็จ / Print Bill",
    print_slip_btn: "พิมพ์ใบลงทะเบียน / Print Slip",
    print_standee_btn: "พิมพ์ป้าย QR / Print QR Sign",
    dispatch_boat_btn: "ปล่อยเรือ / Dispatch Boat",
    status_registering: "กำลังลงทะเบียน / Registering",
    status_cancelled: "ยกเลิก / Cancelled",
    registering_queue: "กำลังลงทะเบียน / Registering Queue",
    ready_checkout_queue: "พร้อมชำระเงิน / Ready to Checkout",

    // Dashboard keys
    payment_method_col: "ช่องทางการชำระ / Payment Method",
    driver_name_col: "คนขับรถ / Driver Name",
    customer_col: "ลูกค้า / Pax",
    commissions_type: "ค่าคอม / Commissions",
    printed_at: "พิมพ์วันที่ / Printed",

    // Ticket Manifest keys
    select_trip_doc: "เลือกเที่ยวเรือเพื่อแสดงเอกสาร / Select Boat Trip:",
    select_trip_option: "เลือกเที่ยวเรือ (Select a Trip)",
    group_bill: "บิลรวมกลุ่ม / Group Bill",
    individual_ticket: "ตั๋วแยกคน / Individual Tickets",
    boat_ticket: "ตั๋วเรือ / Boat Ticket",
    passengers_list: "รายชื่อผู้โดยสาร / Passenger List",
    thank_you: "ขอบคุณที่ใช้บริการ / THANK YOU",
    passenger_manifest_title: "ใบแสดงรายชื่อผู้โดยสาร / Passenger Manifest",
    print_manifest: "พิมพ์ใบรายชื่อ / Print Manifest",
    total_passengers: "ผู้โดยสารทั้งหมด / Total Passengers",
    select_trip_preview: "กรุณาเลือกเที่ยวเรือด้านบนเพื่อแสดงเอกสาร / Select a trip to preview",
    thank_you_short: "ขอบคุณ / THANK YOU",
    boat_ride_insurance: "ล่องเรือ (รวมประกันภัย) / Boat Ride & Insurance",
    reprint_bill_btn: "พิมพ์ใบเสร็จ / Reprint Bill",
    reprint_qr_btn: "พิมพ์สลิป QR / Reprint QR",
    no_edits_logged: "ไม่มีประวัติการแก้ไขบิล / No edits logged for this bill.",
    scan_qr_btn: "สแกน QR Code / QR Scanner",
    enter_code_manually: "ป้อนรหัสกลุ่มหรือสแกนผ่านสาย USB / Enter Group Code Manually",
    group_code_placeholder: "เช่น: REG-1234 หรือ BK-1002",
    customer_instructions: "คำแนะนำสำหรับลูกค้า / Instructions:",
    inst_step1: "1. เปิดกล้องมือถือสแกน QR Code นี้ / 1. Open mobile camera to scan this QR Code",
    inst_step2: "2. กดยอมรับเงื่อนไขความปลอดภัย / 2. Accept safety terms",
    inst_step3: "3. กรอกข้อมูลส่วนตัวให้ครบถ้วนทุกคน แล้วกดบันทึก / 3. Fill details and save",
    close_screen: "ปิดหน้าจอนี้ / Close",
    confirm_cancel_bill: "คุณต้องการยกเลิกบิลนี้ใช่หรือไม่? / Are you sure you want to cancel this bill?",
    bill_edits_saved_alert: "บันทึกการแก้ไขบิลสำเร็จแล้ว! / Bill edits saved successfully!",
    open_bill_btn: "เปิดบิล / Open",
    edit_details_audit: "แก้ไขรายละเอียด, จัดพนักงาน และข้อมูลผู้โดยสาร / Edit details & assign staff",
    discount_label: "ส่วนลด",
    debt_label: "ค้างชำระ",
    net_total_label: "ยอดสุทธิ",
    actual_paid_label: "จ่ายจริง",
    payment_breakdown_title: "สรุปช่องทางชำระเงิน",
    total_discount_label: "ส่วนลดรวม",
    total_debt_label: "ค้างชำระรวม",
    cash_label: "เงินสด",
    transfer_label: "โอน",
    card_label: "บัตร",
    bill_count_label: "บิล"
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLangState] = useState(() => {
    try {
      const saved = localStorage.getItem("pos_lang");
      return saved === "en" || saved === "la" || saved === "th" ? saved : "la";
    } catch (e) {
      return "la";
    }
  });

  const setLang = (newLang) => {
    if (newLang === "en" || newLang === "la" || newLang === "th") {
      setLangState(newLang);
      try {
        localStorage.setItem("pos_lang", newLang);
      } catch (e) {
        console.error(e);
      }
    }
  };

  const t = (key, defaultText) => {
    const val = translations[lang]?.[key];
    if (val !== undefined) return val;
    return defaultText !== undefined ? defaultText : key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
