// LanguageContext.jsx - Global Translation and Rebranding Context Provider
import React, { createContext, useState, useContext } from "react";

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};

const translations = {
  en: {
    // Brand Rebranding
    brand_name: "TADFANE RAFTING",
    brand_name_la: "ຕາດຟານ ລ່ອງແກ່ງ",
    brand_sub: "Rafting Trip Manager",
    system_sub: "Rafting Trip Manager & Employee Accounts (POS)",

    // Sidebar Menus
    dashboard: "Dashboard",
    ticket_sales: "Ticket Sales",
    trips_manifest: "Trips Manifest",
    customer_registration: "Customer Registration",
    commissions: "Commissions",
    guides_live: "Guides Live",
    drivers_live: "Drivers Live",
    boats_live: "Boats Live",
    reports: "Reports",
    financials: "Financials",
    settings: "Settings",
    logout: "Logout",

    // Login screen
    login_email_label: "Employee Email / Email Address",
    login_password_label: "Password",
    login_btn: "Sign In",
    demo_accounts: "Quick Test Accounts",
    login_error: "Invalid email or password!",

    // Inactivity warning
    inactivity_warning_title: "Session Warning",
    inactivity_warning_desc: "You have been inactive for 29 minutes. The system will log out in {time} seconds.",
    keep_working: "Keep Working",

    // Common labels / actions
    pax_unit: "Pax",
    bills_unit: "Bills",
    trips_unit: "Trips",
    passengers_today: "PASSENGERS TODAY",
    total_bills_today: "TOTAL BILLS TODAY",
    trips_today: "TRIPS TODAY",
    revenue_today: "REVENUE TODAY",
    revenue_month: "REVENUE MONTH",
    guide_wages: "GUIDE WAGES",
    driver_wages: "DRIVER WAGES",
    consolidated_report: "CONSOLIDATED REPORT",
    register_new_checkin: "New Check-In",
    system_alerts: "System Alerts",
    loading: "Loading...",

    // Receipt translations
    receipt_title: "POS Bill Preview",
    register_slip: "Register Slip",
    bill_number: "Bill Number",
    booking_id: "Booking ID",
    date: "Date",
    payment: "Payment Method",
    agent: "Agent / Partner",
    passengers: "Passengers",
    driver: "Driver",
    guides: "Guides",
    boats: "Boats",
    notes: "Notes",
    save_changes: "Save Changes",
    edit_label: "Edit",
    print_label: "Print",
    close_label: "Close",

    // Settings
    save_settings: "Save Settings",
    save_all_accounts: "Save Accounts",
    user_permissions_updated: "User accounts and permissions updated successfully!",
    system_settings_updated: "System settings updated!",
    user_added_success: "User added successfully! (Click Save Accounts below to commit)",
    user_deleted_success: "User deleted! (Click Save Accounts below to commit)",
    add_activity: "Add Activity",
    update_activity: "Update Activity",
    login_email: "Login Email",
    password: "Password",
    min_characters: "At least 6 characters",

    // POS Ticketing Complete Translations
    ticket_info_tab: "Ticket Info",
    passengers_tab: "Passengers",
    crew_tab: "Assign Crew",
    new_ticket_title: "Create Ticket Sales / POS",
    cust_name_label: "Customer / Leader Name",
    nation_label: "Nationality",
    age_label: "Age",
    gender_label: "Gender",
    phone_label: "Contact Phone",
    emergency_name_label: "Emergency Name",
    emergency_relation_label: "Relationship",
    emergency_phone_label: "Emergency Phone",
    date_label: "Date",
    time_label: "Time Slot",
    partner_label: "Agent / Partner",
    service_label: "Rafting Activity / Service",
    price_label: "Price",
    payment_method_label: "Payment Method",
    save_btn: "Save Changes",
    cancel_btn: "Cancel",
    confirm_btn: "Confirm",
    unassigned: "Unassigned",
    male: "Male",
    female: "Female",
    other: "Other",

    // Dashboard Completeness
    dashboard_title: "Dashboard Overview",
    dashboard_sub: "Daily operations overview and boat trip revenue statistics",
    daily_bookings: "DAILY BOOKINGS QUEUE",
    trip_manifest_list: "TRIPS MANIFEST LIST",
    all_status: "All Statuses",
    status_pending: "Pending Checkout",
    status_checkedin: "Ready for Dispatch",
    status_dispatched: "On Trip (Dispatched)",
    status_completed: "Completed",
    action_view_bill: "View Bill",
    action_edit: "Edit",
    action_print_bill: "Print Bill",
    action_print_slip: "Print Slip",
    action_print_sign: "Print Standee",
    action_dispatch: "Dispatch",

    // Reports Page
    reports_title: "Business Reports & Profit Summaries",
    reports_sub: "Comprehensive reports on bookings, commissions, costs, and profit breakdown",

    // Live Board Statuses
    available_short: "Avail",
    off_duty_short: "Off",
    ready_short: "Ready",
    not_ready_short: "Not Ready",
    ready_to_depart_short: "Ready",
    maintenance_short: "Maint",
    disabled_short: "Disabled",

    // Accounting / Payroll
    accounting_title: "Accounting & Expenses Portal",
    accounting_sub: "Income, operating expenses, financial reports, and payroll management",
    tab_income: "Income",
    tab_expenses: "Expenses",
    tab_pl: "Profit & Loss",
    tab_reports: "Reports",
    run_payroll: "Run Payroll",
    print_statement: "Print Statement",
    pending_approval: "Pending Approval Queue",
    record_expense: "Record Operating Expense",
    save_expense: "Save Expense",
    general_expenses: "General Expenses Statement List",
    expense_category: "Expense Category",
    calculation_details: "Calculation Details",
    monthly_amount: "Monthly Amount (LAK)",
    total_expenses: "TOTAL OPERATING EXPENSES",
    total_revenue: "TOTAL REVENUE",
    gross_profit: "Gross Profit",
    net_profit: "Net Profit",
    agent_commissions_due: "Agent Commissions Due",
    wages_due: "Crew Wages Due",
    monthly_salaries: "Monthly Salaries",
    back_to_expenses: "Back to Expenses",
    back_to_income: "Back to Income",
    no_records: "No records found.",
        confirm_delete_expense: "Are you sure you want to delete this expense?",
    // Commission Tracker keys
    commission_report: "Referral Commission Summary",
    partner_name_col: "Partner / Agent Name",
    type_col: "Type",
    rate_col: "Rate",
    pax_count_col: "Referred Passengers",
    comm_due_col: "Commission Earned",
    action_col: "Manage",
    type_company: "Tour Company",
    type_agent: "Agent",
    type_guide: "Guide Referral",
    partner_details: "Referral Partner Details",
    contact_label: "Contact Info",
    rate_pax: "Commission Rate",
    total_referred: "Total Referred Passengers",
    total_commission: "Total Accumulated Commission",
    monthly_summary: "Monthly Commission Summary",
    no_monthly_history: "No monthly referral history.",
    pax_count_label: "Pax Count",
    clear_filter: "Clear Filter",
    edit_partner: "Edit Partner Details",
    add_partner: "Add New Partner",
    partner_name_field: "Tour Company / Agent Name",
    partner_name_placeholder: "e.g. Tad Fane Discoveries",
    partner_type_field: "Partner Type",
    commission_rate_field: "Commission Rate per Pax (LAK)",
    contact_info_field: "Contact Phone / Email",
    contact_info_placeholder: "e.g. +856 20 99998888",
    save_partner_btn: "Save Partner",
    cancel_partner_btn: "Cancel",
    confirm_delete_partner: "Are you sure you want to delete this partner?",
    referrals_monthly_title: "Referrals for",
                referrals_all_title: "All Referred Passengers",
    // QRBooking / POS keys
    ticket_sales_assignee: "Ticket Sales",
    tour_dispatch_assignee: "Tour Dispatch",
    select_multiple_guides: "Select one or more guides",
    select_multiple_boats: "Select one or more boats",
    select_one_driver: "Select exactly one driver",
    save_assignments: "Save Assignments",
    complete_trip: "Complete Trip",
    cancel_bill: "Cancel Bill",
    audit_logs_title: "Audit Logs:",
    edit_bill_desc: "Edit details, assign staff and passenger information",
    bill_details_tab: "Bill Details",
    audit_logs_tab: "Audit Logs",
    price_tier_label: "Price Tier (THB Activities)",
    price_tier1: "Standard Price (Tier 1 / Flat)",
    price_tier3: "Promo / Group Price (Tier 3)",
    custom_price_label: "Custom Price per Pax (Optional)",
    custom_price_placeholder: "Leave empty to use standard price",
    cash_payment: "Cash (LAK)",
    qr_payment: "Bank QR Transfer",
    notes_placeholder: "Any additional notes...",
    recalculated_total: "Recalculated Total:",
    flat_rate: "Flat",
    per_pax: "per Pax",
    passenger_number: "Passenger #",
    save_edits_btn: "Save Edits",
    cancel_edits_btn: "Cancel Edits",
    paid_bill_indicator: "Paid Bill",
    edit_paid_bill_audit: "Audit Logger Active (Editing Paid Bill)",
    billing_terminal: "Billing Terminal",
    search_bill_placeholder: "Scan or enter Bill Number / Booking Code...",
    new_booking_btn: "New Bill / Group",
    walkin_label: "Walk-in (General Guest)",
    no_crew_warning: "Boat crew and boat must be assigned first!",
    no_driver_warning: "No driver assigned.",
    print_bill_btn: "Print Bill",
    print_slip_btn: "Print Slip",
    print_standee_btn: "Print QR Sign",
    dispatch_boat_btn: "Dispatch Boat",
    status_registering: "Registering",
    status_cancelled: "Cancelled",
    registering_queue: "Registering Queue",
    ready_checkout_queue: "Ready to Checkout",
    // Dashboard keys
    payment_method_col: "Payment Method",
    driver_name_col: "Driver Name",
    customer_col: "Customer / Pax",
    commissions_type: "Commissions",
    printed_at: "Printed at",
    // Ticket Manifest keys
    select_trip_doc: "Select Boat Trip:",
    select_trip_option: "Select a Trip",
    group_bill: "Group Bill",
    individual_ticket: "Individual Tickets",
    boat_ticket: "Boat Ticket",
    passengers_list: "Passenger List",
    thank_you: "THANK YOU FOR USING OUR SERVICES",
    passenger_manifest_title: "Passenger Manifest",
    print_manifest: "Print Manifest",
    total_passengers: "Total Passengers",
    select_trip_preview: "Please select a boat trip from above to preview documents.",
    thank_you_short: "THANK YOU",
    boat_ride_insurance: "Boat Ride (Insurance Included)",
    reprint_bill_btn: "Reprint Bill",
    reprint_qr_btn: "Reprint QR",
    no_edits_logged: "No edits logged for this bill.",
    scan_qr_btn: "QR Scanner",
    enter_code_manually: "Enter Group Code Manually",
    group_code_placeholder: "e.g. REG-1234 or BK-1002",
    customer_instructions: "Instructions:",
    inst_step1: "1. Open mobile camera to scan this QR Code",
    inst_step2: "2. Accept safety terms",
    inst_step3: "3. Fill in details and click save",
    close_screen: "Close",
    confirm_cancel_bill: "Are you sure you want to cancel this bill?",
    bill_edits_saved_alert: "Bill edits saved successfully!",
    open_bill_btn: "Open",
    edit_details_audit: "Edit details, assign staff and passenger information"
  },
  la: {
    // Brand Rebranding
    brand_name: "ຕາດຟານ ລ່ອງແກ່ງ",
    brand_name_la: "ຕາດຟານ ລ່ອງແກ່ງ",
    brand_sub: "ລະບົບຈັດການການລ່ອງແກ່ງ",
    system_sub: "ລະບົບຈັດການການລ່ອງແກ່ງ ແລະ ບັນຊີພະນັກງານ (POS)",

    // Sidebar Menus
    dashboard: "ໜ້າຫຼັກ",
    ticket_sales: "ຂາຍປີ້",
    trips_manifest: "ລາຍການຖ້ຽວ",
    customer_registration: "ລົງທະບຽນລູກຄ້າ",
    commissions: "ຄ່າຄອມເອເຈນ",
    guides_live: "ຕິດຕາມໄກດ໌",
    drivers_live: "ຕິດຕາມຄົນຂັບ",
    boats_live: "ຕິດຕາມເຮືອ",
    reports: "ລາຍງານ",
    financials: "ການເງິນ",
    settings: "ຕັ້ງຄ່າ",
    logout: "ອອກຈາກລະບົບ",

    // Login screen
    login_email_label: "ອີເມວພະນັກງານ / Email Address",
    login_password_label: "ລະຫັດຜ່ານ / Password",
    login_btn: "ເຂົ້າສູ່ລະບົບ / Sign In",
    demo_accounts: "ບັນຊີທົດລອງໃຊ້ງານ / Quick Test Accounts",
    login_error: "ອີເມວ ຫຼື ຣະຫັດຜ່ານບໍ່ຖືກຕ້ອງ!",

    // Inactivity warning
    inactivity_warning_title: "ແຈ້ງເຕືອນໝົດເວລາໃຊ້ງານ",
    inactivity_warning_desc: "ທ່ານບໍ່ມີການເຄື່ອນໄຫວເປັນເວລາ 29 ນາທີ. ລະບົບຈະອອກຈາກລະບົບໃນອີກ {time} ວິນາທີ.",
    keep_working: "ເຮັດວຽກຕໍ່ / Keep Working",

    // Common labels / actions
    pax_unit: "ຄົນ (Pax)",
    bills_unit: "ບິນ (Bills)",
    trips_unit: "ທ່ຽວ (Trips)",
    passengers_today: "ລູກຄ້າວັນນີ້ / PASSENGERS TODAY",
    total_bills_today: "ບິນທັງໝົດວັນນີ້ / TOTAL BILLS TODAY",
    trips_today: "ທ່ຽວເຮືອວັນນີ້ / TRIPS TODAY",
    revenue_today: "ລາຍຮັບວັນນີ້ / REVENUE TODAY",
    revenue_month: "ລາຍຮັບເດືອນນີ້ / REVENUE MONTH",
    guide_wages: "ຄ່າທ່ຽວໄກ້ດ / GUIDE WAGES",
    driver_wages: "ຄ່າທ່ຽວຄົນຂັບລົດ / DRIVER WAGES",
    consolidated_report: "ສະຫຼຸບຂໍ້ມູນທັງໝົດ / CONSOLIDATED REPORT",
    register_new_checkin: "Check-In ໃໝ່",
    system_alerts: "ແຈ້ງເຕືອນລະບົບ / System Alerts",
    loading: "ກຳລັງໂຫລດ...",

    // Receipt translations
    receipt_title: "ບິນຮັບເງິນ / POS Bill Preview",
    register_slip: "ບິນລົງທະບຽນລູກຄ້າ / Register Slip",
    bill_number: "ເລກບິນ / Bill Number",
    booking_id: "ລະຫັດການຈອງ / Booking ID",
    date: "ວັນທີ / Date",
    payment: "ການຊຳລະເງິນ / Payment",
    agent: "ຕົວແທນ / Agent",
    passengers: "ຜູ້ໂດຍສານ / Passengers",
    driver: "ຄົນຂັບ / Driver",
    guides: "ໄກດ໌ / Guides",
    boats: "ເຮືອ / Boats",
    notes: "ບັນທຶກ / Notes",
    save_changes: "ບັນທຶກການແກ້ໄຂ / Save Changes",
    edit_label: "ແກ້ໄຂ / Edit",
    print_label: "ພິມ / Print",
    close_label: "ປິດ / Close",

    // Settings
    save_settings: "ບັນທຶກການຕັ້ງຄ່າ / Save Settings",
    save_all_accounts: "ບັນທຶກຂໍ້ມູນບັນຊີທັງໝົດ / Save Accounts",
    user_permissions_updated: "ບັນທຶກຂໍ້ມູນບັນຊີຜູ້ໃຊ້ ແລະ ສິດພະນັກງານຮຽບຮ້ອຍ!",
    system_settings_updated: "ບັນທຶກການຕັ້ງຄ່າລະບົບຮຽບຮ້ອຍ!",
    user_added_success: "ເພີ່ມບັນຊີຜູ້ໃຊ້ພະນັກງານຮຽບຮ້ອຍ! (ກົດບັນທຶກບັນຊີດ້ານລຸ່ມເພື່ອບັນທຶກ)",
    user_deleted_success: "ລົບບັນຊີສຳເລັດ! (ກົດບັນທຶກບັນຊີດ້ານລຸ່ມເພື່ອບັນທຶກ)",
    add_activity: "ເພີ່ມກິດຈະກຳ / Add Activity",
    update_activity: "ບັນທຶກການແກ້ໄຂ / Update Activity",
    login_email: "ອີເມວເຂົ້າໃຊ້ງານ / Login Email",
    password: "ລະຫັດຜ່ານ / Password",
    min_characters: "ຢ່າງໜ້ອຍ 6 ຕົວອັກສອນ",

    // POS Ticketing Complete Translations
    ticket_info_tab: "ຂໍ້ມູນການຈອງ",
    passengers_tab: "ລາຍຊື່ຜູ້ໂດຍສານ",
    crew_tab: "ຈັດພະນັກງານ",
    new_ticket_title: "ລະບົບຂາຍປີ້ ແລະ ອອກບິນ / POS Terminal",
    cust_name_label: "ຊື່ລູກຄ້າ (ຫົວໜ້າກຸ່ມ)",
    nation_label: "ສັນຊາດ",
    age_label: "ອາຍຸ",
    gender_label: "ເພດ",
    phone_label: "ເບີໂທຕິດຕໍ່",
    emergency_name_label: "ຊື່ຜູ້ຕິດຕໍ່ສຸກເສີນ",
    emergency_relation_label: "ຄວາມສຳພັນ",
    emergency_phone_label: "ເບີໂທສຸກເສີນ",
    date_label: "ວັນທີເດີນທາງ",
    time_label: "ຮອບເວລາ",
    partner_label: "ຕົວແທນ / ເອເຈນ",
    service_label: "ກິດຈະກຳ / ບໍລິການ",
    price_label: "ລາຄາ (LAK)",
    payment_method_label: "ວິທີການຊຳລະເງິນ",
    save_btn: "ບັນທຶກຂໍ້ມູນ / Save",
    cancel_btn: "ຍົກເລີກ / Cancel",
    confirm_btn: "ຢືນຢັນ / Confirm",
    unassigned: "ຍັງບໍ່ໄດ້ກຳນົດ",
    male: "ຊາຍ",
    female: "ຍິງ",
    other: "ອື່ນໆ",

    // Dashboard Completeness
    dashboard_title: "ແຜງຄວບຄຸມ (Dashboard)",
    dashboard_sub: "ພາບລວມການດຳເນີນງານປະຈຳວັນ ແລະ ລາຍຮັບເຮືອທ່ອງທ່ຽວ",
    daily_bookings: "ຄິວການຈອງປະຈຳວັນ",
    trip_manifest_list: "ລາຍການຖ້ຽວເດີນທາງວັນນີ້",
    all_status: "ທຸກສະຖານະ",
    status_pending: "ລໍຖ້າຊຳລະເງິນ",
    status_checkedin: "ພ້ອມເດີນທາງ / Check-In",
    status_dispatched: "ກຳລັງເດີນທາງ",
    status_completed: "ສຳເລັດແລ້ວ",
    action_view_bill: "ເບິ່ງບິນ",
    action_edit: "ແກ້ໄຂ",
    action_print_bill: "ພິມໃບບິນ",
    action_print_slip: "ພິມໃບລົງທະບຽນ",
    action_print_sign: "ພິມປ້າຍ QR",
    action_dispatch: "ປ່ອຍເຮືອ",

    // Reports Page
    reports_title: "ລາຍງານການເງິນ ແລະ ສະຫຼຸບຜົນກຳໄລ",
    reports_sub: "ລາຍງານລາຍຮັບ-ລາຍຈ່າຍ ຄ່າຄອມມິດຊັນ ແລະ ສະຫຼຸບຜົນກຳໄລທັງໝົດ",

    // Live Board Statuses
    available_short: "ຫວ່າງ",
    off_duty_short: "ຢຸດງານ",
    ready_short: "ພ້ອມໃຊ້",
    not_ready_short: "ບໍ່ພ້ອມ",
    ready_to_depart_short: "ພ້ອມອອກ",
    maintenance_short: "ລໍຊ້ອມ",
    disabled_short: "ປິດໃຊ້",

    // Accounting / Payroll
    accounting_title: "ລະບົບບັນຊີ ແລະ ລາຍຈ່າຍ",
    accounting_sub: "ສະຫຼຸບລາຍຮັບ-ລາຍຈ່າຍ, ການອະນຸມັດວົງເງິນ ແລະ ຈັດການເງິນເດືອນ",
    tab_income: "ລາຍຮັບ",
    tab_expenses: "ລາຍຈ່າຍ",
    tab_pl: "ກຳໄລ-ຂາດທຶນ",
    tab_reports: "ລາຍງານ",
    run_payroll: "ຈັດການເງິນເດືອນ",
    print_statement: "ພິມລາຍງານ",
    pending_approval: "ລາຍການລໍຖ້າການອະນຸມັດ",
    record_expense: "ບັນທຶກລາຍຈ່າຍໃໝ່",
    save_expense: "ບັນທຶກລາຍຈ່າຍ",
    general_expenses: "ລາຍການລາຍຈ່າຍທົ່ວໄປ",
    expense_category: "ປະເພດລາຍຈ່າຍ",
    calculation_details: "ລາຍລະອຽດການຄຳນວນ",
    monthly_amount: "ຍອດເງິນປະຈຳເດືອນ (LAK)",
    total_expenses: "ລວມລາຍຈ່າຍທັງໝົດ",
    total_revenue: "ລວມລາຍຮັບທັງໝົດ",
    gross_profit: "ກຳໄລຂັ້ນຕົ້ນ",
    net_profit: "ກຳໄລສຸດທິ",
    agent_commissions_due: "ຄ່າຄອມມິດຊັນເອເຈນ",
    wages_due: "ຄ່າ allowance ພະນັກງານ",
    monthly_salaries: "ເງິນເດືອນພະນັກງານປະຈຳ",
    back_to_expenses: "ກັບຄືນສູ່ໜ້າລາຍຈ່າຍ",
    back_to_income: "ກັບຄືນສູ່ໜ້າລາຍຮັບ",
    no_records: "ບໍ່ມີຂໍ້ມູນ.",
    confirm_delete_expense: "ທ່ານຕ້ອງການລຶບລາຍຈ່າຍນີ້ແມ່ນບໍ່?",
    // Commission Tracker keys
    commission_report: "ລາຍງານຄ່າຄອມມິດຊັນສະສົມ / Commission Report",
    partner_name_col: "ຊື່ຄູ່ຄ້າ / Partner",
    type_col: "ປະເພດ / Type",
    rate_col: "ອັດຕາຄ່າຫົວ / Rate",
    pax_count_col: "ຜູ້ໂດຍສານສະສົມ / Passengers",
    comm_due_col: "ຍອດເງິນຄອມ / Commission",
    action_col: "ຈັດການ / Actions",
    type_company: "ບໍລິສັດທົວ / Tour Company",
    type_agent: "ເອເຈນ / Agent",
    type_guide: "ໄກ້ດແນະນຳ / Guide",
    partner_details: "ລາຍລະອຽດຄູ່ຄ້າ / Partner Details",
    contact_label: "ຕິດຕໍ່ / Contact",
    rate_pax: "ເລດຄ່າຄອມ / Rate",
    total_referred: "ລວມຜູ້ແນະນຳທັງໝົດ / Total Referred",
    total_commission: "ຍອດເງິນສະສົມທັງໝົດ / Total Commission",
    monthly_summary: "ສະຫຼຸບຍອດລາຍເດືອນ / Monthly Summary",
    no_monthly_history: "ຍັງບໍ່ມີປະຫວັດການສົ່ງຍອດລູກຄ້າລາຍເດືອນ.",
    pax_count_label: "ຈຳນວນຄົນ",
    clear_filter: "ລ້າງການກັ່ນຕອງ / Clear Filter",
    edit_partner: "ແກ້ໄຂຂໍ້ມູນຄູ່ຄ້າ / Edit Partner",
    add_partner: "ເພີ່ມບໍລິສັດຄູ່ຄ້າ / Add New Partner",
    partner_name_field: "ຊື່ອີເຈນ / ບໍລິສັດທົວ (Partner Name) *",
    partner_name_placeholder: "ຕົວຢ່າງ: ບໍລິສັດ ຕາດຟານ ດີດຄັຟເວີຣີ ຈຳກັດ",
    partner_type_field: "ປະເພດ (Type)",
    commission_rate_field: "ຄ່າຄອມຕໍ່ຫົວ / Rate (LAK) *",
    contact_info_field: "ເບີຕິດຕໍ່ / ລາຍລະອຽດ (Contact Info)",
    contact_info_placeholder: "ເບີໂທລະສັບ ຫຼື ອີເມວ",
    save_partner_btn: "ບັນທຶກຂໍ້ມູນຄູ່ຄ້າ / Save Partner",
    cancel_partner_btn: "ຍົກເລີກ / Cancel",
    confirm_delete_partner: "ທ່ານຕ້ອງການລົບຄູ່ຄ້ານີ້ແທ້ບໍ? / Delete partner?",
    referrals_monthly_title: "ລາຍຊື່ແນະນຳປະຈຳເດືອນ",
                referrals_all_title: "ລາຍຊື່ລູກຄ້າແນະນຳທັງໝົດ (All Referrals)",
    // QRBooking / POS keys
    ticket_sales_assignee: "ຜູ້ຮັບຜິດຊອບງານຂາຍປີ້ / Ticket Sales",
    tour_dispatch_assignee: "ຜູ້ຮັບຜິດຊອບຈັດໄກ້ດ / Tour Dispatch",
    select_multiple_guides: "ເລືອກໄດ້ຫຼາຍກວ່າ 1 ຄົນ",
    select_multiple_boats: "ເລືອກໄດ້ຫຼາຍກວ່າ 1 ລຳ",
    select_one_driver: "ເລືອກໄດ້ 1 ຄົນເທົ່ານັ້ນ",
    save_assignments: "ບັນທຶກການຈັດພະນັກງານ / Save Assignments",
    complete_trip: "ສຳເລັດທຣິບ / Complete Trip",
    cancel_bill: "ຍົກເລີກບິນ / Cancel Bill",
    audit_logs_title: "ປະຫວັດການແກ້ໄຂບິນ / Audit Logs:",
    edit_bill_desc: "ແກ້ໄຂລາຍລະອຽດ, ຈັດພະນັກງານ ແລະ ຂໍ້ມູນຜູ້ໂດຍສານ",
    bill_details_tab: "ລາຍລະອຽດບິນ / Bill Details",
    audit_logs_tab: "ປະຫວັດການແກ້ໄຂ / Audit Logs",
    price_tier_label: "ລະດັບລາຄາ / Price Tier",
    price_tier1: "ລາຄາເລີ່ມຕົ້ນ (Tier 1 / Flat)",
    price_tier3: "ລາຄາໂປຣໂມຊັ່ນ/ກຸ່ມໃຫຍ່ (Tier 3)",
    custom_price_label: "ລາຄາຕັ້ງເອງ / Custom Price",
    custom_price_placeholder: "ປະວ່າງໄວ້ເພື່ອໃຊ້ລາຄາເລີ່ມຕົ້ນ",
    cash_payment: "ເງິນສົດ / Cash (LAK)",
    qr_payment: "ແກນ QR / Bank QR Transfer",
    notes_placeholder: "ໝາຍເຫດເພີ່ມເຕີມ...",
    recalculated_total: "ລາຄາສຸດທິໃໝ່ / Recalculated Total:",
    flat_rate: "ເໝົາລຳ",
    per_pax: "ຕໍ່ຄົນ",
    passenger_number: "ຜູ້ໂດຍສານຄົນທີ",
    save_edits_btn: "ບັນທຶກການແກ້ໄຂ / Save Edits",
    cancel_edits_btn: "ຍົກເລີກການແກ້ໄຂ / Cancel Edits",
    paid_bill_indicator: "ບິນນີ້ຊຳລະເງິນແລ້ວ / Paid Bill",
    edit_paid_bill_audit: "ກຳລັງແກ້ໄຂຂໍ້ມູນບິນທີ່ຈ່າຍເງິນແລ້ວ (Audit Logger Active)",
    billing_terminal: "ລະບົບຂາຍປີ້ ແລະ ອອກບິນ / Billing Terminal",
    search_bill_placeholder: "ສະແກນ ຫຼື ປ້ອນເລກບິນ / ລະຫັດການຈອງ...",
    new_booking_btn: "ສ້າງບິນໃໝ່ / New Bill Group",
    walkin_label: "ລູກຄ້າທົ່ວໄປ (Walk-in)",
    no_crew_warning: "ກະລຸນາຈັດເຮືອ ແລະ ພະນັກງານກ່ອນປ່ອຍເຮືອ!",
    no_driver_warning: "ບໍ່ມີຄົນຂັບລົດ.",
    print_bill_btn: "ພິມໃບບິນ / Print Bill",
    print_slip_btn: "ພິມໃບລົງທະບຽນ / Print Slip",
    print_standee_btn: "ພິມປ້າຍ QR / Print QR Sign",
    dispatch_boat_btn: "ປ່ອຍເຮືອ / Dispatch Boat",
    status_registering: "ກຳລັງລົງທະບຽນ / Registering",
    status_cancelled: "ຍົກເລີກ / Cancelled",
    registering_queue: "ກຳລັງລົງທະບຽນ / Registering Queue",
    ready_checkout_queue: "ພ້ອມຊຳລະເງິນ / Ready to Checkout",
    // Dashboard keys
    payment_method_col: "ຊ່ອງທາງການຊຳລະ / Payment Method",
    driver_name_col: "ຄົນຂັບລົດ / Driver Name",
    customer_col: "ລູກຄ້າ / Pax",
    commissions_type: "ຄ່າຄອມ / Commissions",
    printed_at: "ພິມວັນທີ / Printed",
    // Ticket Manifest keys
    select_trip_doc: "ເລືອກທ່ຽວເຮືອເພື່ອສະແດງເອກະສານ / Select Boat Trip:",
    select_trip_option: "ເລືອກທ່ຽວເຮືອ (Select a Trip)",
    group_bill: "ບິນລວມກຸ່ມ / Group Bill",
    individual_ticket: "ປີ້ແຍກຄົນ / Individual Tickets",
    boat_ticket: "ປີ້ເຮືອ / Boat Ticket",
    passengers_list: "ລາຍຊື່ຜູ້ໂດຍສານ / Passenger List",
    thank_you: "ຂອບໃຈທີ່ໃຊ້ບໍລິການ / THANK YOU",
    passenger_manifest_title: "ໃບສະແດງລາຍຊື່ຜູ້ໂດຍສານ / Passenger Manifest",
    print_manifest: "ພິມໃບລາຍຊື່ / Print Manifest",
    total_passengers: "ຜູ້ໂດຍສານທັງໝົດ / Total Passengers",
    select_trip_preview: "ກະລຸນາເລືອກທ່ຽວເຮືອດ້ານເທິງເພື່ອສະແດງເອກະສານ / Select a trip to preview",
    thank_you_short: "ຂອບໃຈ / THANK YOU",
    boat_ride_insurance: "ລ່ອງເຮືອ (ລວມປະກັນໄພ) / Boat Ride & Insurance",
    reprint_bill_btn: "ພິມໃບບິນ / Reprint Bill",
    reprint_qr_btn: "ພິມສລິບ QR / Reprint QR",
    no_edits_logged: "ບໍ່ມີປະຫວັດການແກ້ໄຂບິນ / No edits logged for this bill.",
    scan_qr_btn: "ສະແກນ QR Code / QR Scanner",
    enter_code_manually: "ປ້ອນລະຫັດກຸ່ມ ຫຼື ສະແກນຜ່ານສາຍ USB / Enter Group Code Manually",
    group_code_placeholder: "ເຊັ່ນ: REG-1234 ຫຼື BK-1002",
    customer_instructions: "ຄຳແນະນຳສຳລັບລູກຄ້າ / Instructions:",
    inst_step1: "1. ເປີດກ້ອງມືຖືສະແກນ QR Code ນີ້ / 1. Open mobile camera to scan this QR Code",
    inst_step2: "2. ກົດຍອມຮັບເງື່ອນໄຂຄວາມປອດໄພ / 2. Accept safety terms",
    inst_step3: "3. ກອກຂໍ້ມູນສ່ວນຕົວໃຫ້ຄົບຖ້ວນທຸກຄົນ ແລ້ວກົດບັນທຶກ / 3. Fill details and save",
    close_screen: "ປິດໜ້າຈໍນີ້ / Close",
    confirm_cancel_bill: "ທ່ານຕ້ອງການຍົກເລີກບິນນີ້ແມ່ນຫຼືບໍ່? / Are you sure you want to cancel this bill?",
    bill_edits_saved_alert: "ບັນທຶກການແກ້ໄຂບິນສຳເລັດແລ້ວ! / Bill edits saved successfully!",
    open_bill_btn: "ເປີດບິນ / Open",
    edit_details_audit: "ແກ້ໄຂລາຍລະອຽດ, ຈັດພະນັກງານ ແລະ ຂໍ້ມູນຜູ້ໂດຍສານ / Edit details & assign staff"
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLangState] = useState(() => {
    try {
      const saved = localStorage.getItem("pos_lang");
      return saved === "en" || saved === "la" ? saved : "la";
    } catch (e) {
      return "la";
    }
  });

  const setLang = (newLang) => {
    if (newLang === "en" || newLang === "la") {
      setLangState(newLang);
      try {
        localStorage.setItem("pos_lang", newLang);
      } catch (e) {
        console.error(e);
      }
    }
  };

  const t = (key, defaultText) => {
    const val = translations[lang]?.[key];
    if (val !== undefined) return val;
    return defaultText !== undefined ? defaultText : key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
